apiVersion: v1
kind: Service
metadata:
  name: supermercado-service
spec:
  selector:
    app: supermercado-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
